name: 🚀 Feature Request
description: Suggest new feature advice or improvements
title: '[Feat]: '
body:
  - type: markdown
    attributes:
      value: Thanks for the feature suggestions, we will consider them carefully!
  - type: textarea
    id: summary
    attributes:
      label: Introduction
      description: Simple explain what this feature to solve the problem
      placeholder: This feature will resloved...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What solution do you hope to see?
      description: Describe clearly and concisely what you hope will happen.
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: What alternative solutions have you considered?
      description: >-
        Describe clearly and concisely any alternative solutions or features you
        have considered.
  - type: textarea
    id: screenshot
    attributes:
      label: Do you have any other context or screenshot?
      description: >-
        Add any other context or screenshots regarding the function request
        here.
  - type: textarea
    id: systeminfo
    attributes:
      label: systemInfo
      placeholder: System, Binaries, Browsers
  - type: checkboxes
    id: contribute
    attributes:
      label: Intention to contribute
      options:
        - label: >-
            I'm interested in working on specific features and contributing back
            to the upstream community
          required: false
  - type: markdown
    attributes:
      value: >-
        This template was generated with [Issue Forms
        Creator](https://issue-forms-creator.netlify.app)
